update curl install

diff --git a/Dockerfile.pi b/Dockerfile.pi
--- a/Dockerfile.pi
+++ b/Dockerfile.pi
@@ -15,14 +15,14 @@ RUN java -Djarmode=layertools -jar application.jar extract
 FROM ${BASE_IMAGE}
 # Install curl for health check (using a Debian-based package manager since the image is Debian-based)
 # Install essential tools for health checks
-RUN if command -v apk > /dev/null; then \
-        apk --no-cache add curl; \
-    elif command -v apt-get > /dev/null; then \
-        apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*; \
-    else \
-        echo "Package manager not found. Cannot install curl."; \
-        exit 1; \
-    fi
+#RUN if command -v apk > /dev/null; then \
+#        apk --no-cache add curl; \
+#    elif command -v apt-get > /dev/null; then \
+#        apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*; \
+#    else \
+#        echo "Package manager not found. Cannot install curl."; \
+#        exit 1; \
+#    fi
 # Add a jenkins user for enhanced security
 RUN groupadd --system jenkins && \
     useradd --system --gid jenkins --home-dir /home/jenkins --create-home jenkins
